### PR TITLE
fix: Dokan reports not updated after modification of order amount from admin

### PR DESCRIPTION
**Pull request by kapilpaul**
fix: Reports not updated after modification of order amount from admin

### CODE REVIEW

**Review by xaviranik — COMMENTED** [review]
it looks fine.

**Comment by FaraziF** [comment]
@kapilpaul bhai, is it the right scenario?
If admin updates order amount from admin dashboard like 100 to 120 then updated amount 20 will apply only for vendor earning, not admin commission.

**Comment by kapilpaul** [comment]
@FaraziF bhai, if the admin updates the order amount like 100 to 120, then the order total will be 120. admin will get his commission from the order total and the rest is for the vendor.

**Comment by FaraziF** [comment]
Within the scenario, Admin can not get commissions from the updated amount. please review the [video](https://www.awesomescreenshot.com/video/2013630?key=917d1332e3c726528b4a5c8ebc484148)

**Comment by FaraziF** [comment]
Vendor earning not updated when order amount update from admin.

**Comment by nurul-umbhiya** [comment]
@kapilpaul I'm not merging this pr now. will discuss dependency with payment gateways.

**Comment by Mohaiminulislam1989** [comment]
Invalid.

**Pull request closed without merging**
