### PR TITLE
feat: allow customer to insert admin coupon on order

### PR DESCRIPTION
**Pull request by saimonh3**

### CODE REVIEW

**Comment by saimonh3** [comment]
**Admin will be able to choose who will bear the coupon discount which will be created by the marketplace.**

Screen Shot 2019-12-13 at 2 45 33 PM

**Comment by trajche** [comment]
Tested the following cases:
- Adding a global coupon for all products
- Adding a global coupon just on WooCommerce Subscriptions based products
- Testing with 'random' coupons to see if there are any calculation issues

Works beautifully! Thanks for this - waiting for the merge 👍

**Comment by saimonh3** [comment]
@trajche Thanks, it will be merged soon.

**Comment by trajche** [comment]
@saimonh3 Any ETA on merging this? We've been doing the manual editing after each update.

**Comment by trajche** [comment]
Since this is not getting merged, I have created a patch here for every update:
https://gist.github.com/trajche/6be4350f472b6fd3eca2053e240c5c17
In case anyone else needs it, you can download it and apply the patch with `git am allow-admin-coupons-fix.patch`

**Comment by alamgircsebd** [comment]
Here have conflicting errors, right now we can't marge this PR because we have refactor full plugin structure after v3.0.0  
This features not requested any more, if some need this feature please submit a request here - https://wedevs.com/account/dokan-feature-requests/

**Pull request closed without merging**
