### PR TITLE
update: Blank product page UI changed on vendor dashboard

### PR DESCRIPTION
**Pull request by alamgircsebd**
How look like the UI

Screenshot_10

### CODE REVIEW

**Comment by kapilpaul** [comment]
yes its nice. The icon is a little bit big in size, seems to me.

**Comment by Mohaiminulislam1989** [comment]
@alamgircsebd  please check this https://ibb.co/x8trYZx.

**Comment by tuhin480** [comment]
Please have a look @alamgircsebd 
https://prnt.sc/wgpclw

**Comment by alamgircsebd** [comment]
New design
Screenshot(1)

**Pull request merged**
