### PR TITLE
Split orders in admin dashboard.

### PR DESCRIPTION
**Pull request by mi5t4n**
Split the order when the order containing products from multiple vendors is created from the admin dashboard.

### CODE REVIEW

**Comment by mi5t4n** [comment]
@tareq1988 can you check the pull request?

**Comment by saimonh3** [comment]
@mi5t4n Thanks for the PR. It does split the order but order status on the sub orders doesn't seems working accordingly. Would you check?

**Comment by mi5t4n** [comment]
ok i will check it.

**Comment by mi5t4n** [comment]
@saimonh3 I have checked it. The status of the suborders can also be changed from the admin dashboard as well as the seller dashboard. The order status of the suborders also changes to the parent order status. Can you verify it on your end, it is working on my end.

**Comment by saimonh3** [comment]
@mi5t4n When the parent order status is anything else other than 'pending payment' it doesn't work. For example, if the parent order status is 'processing' while creating the order, all the sub orders status should be 'processing' as well.

**Comment by mi5t4n** [comment]
@saimonh3 Thank you for your response. As you said, indeed the status of the suborder is not set to the status of the parent order when the order is created with a status other than processing. I have changed the code and committed. Please verify on your end.

**Comment by saimonh3** [comment]
@mi5t4n It works now. Thanks for PR.

**Comment by mi5t4n** [comment]
@saimonh3 Thank You too.

**Pull request merged**
