### PR TITLE
Introduce the filter hook `dokan_dashboard_nav_settings_key`

### PR DESCRIPTION
**Pull request by strategio**
Replacing https://github.com/OnTheGoSystems/dokan/pull/1 on OTGS fork.

https://github.com/weDevsOfficial/dokan-wpml/issues/12

### CODE REVIEW

**Comment by strategio** [comment]
@alamgircsebd, @nurul-umbhiya, I have a bunch of other PRs on OTGS forks (most PRs are depending on previous ones):
https://github.com/weDevsOfficial/dokan-wpml/pull/14 (APPROVED)
https://github.com/OnTheGoSystems/dokan/pull/1 (CANCELLED) => Replaced by the current PR.
https://github.com/OnTheGoSystems/dokan-wpml/pull/1 (PENDING)
https://github.com/OnTheGoSystems/dokan/pull/2 (PENDING)
https://github.com/OnTheGoSystems/dokan-wpml/pull/2 (PENDING)


It would make our lifes easier if you could grant me a "developer" access to Dokan Lite and Dokan WPML github repositories. This means I will be able to create patch branches on your repo so I can target one of my branches which is not merged yet and open a PR on your repo for it.

**Comment by nurul-umbhiya** [comment]
@tareq1988 Bhai can you please grant developer access for @strategio for Dokan lite and Dokan WPML repo?

**Comment by nurul-umbhiya** [comment]
@strategio we will not be able to provide developer access. But if you need any kind of help regarding your PR, let me know, I'll be happy to help you.

**Comment by strategio** [comment]
@nurul-umbhiya, as explained, my branches are targeting each others. For instance, on this PR https://github.com/OnTheGoSystems/dokan/pull/2 (on our fork), we have the branch `dokan-wpml/issues/13` targeting `dokan-wpml/issues/12`. So I need to wait for each branch to be merged in your repo before to open a new PR on your repo. In the end, I need to do the work twice and I need come back again and again on these tasks while everything is completed on my side.

If can't grant me a "developer" access to you repo (even temporarily), please replicate my PRs on your repo by duplicating my branches.

I am sharing again all the code changes required:
- weDevsOfficial/dokan-wpml#14 (APPROVED)
- OnTheGoSystems#1 (CANCELLED) => Replaced by the current PR.
- OnTheGoSystems/dokan-wpml#1 (PENDING)
- OnTheGoSystems#2 (PENDING)
- OnTheGoSystems/dokan-wpml#2 (PENDING)

**Review by nurul-umbhiya — APPROVED** [review]

**Pull request merged**
