### PR TITLE
Extend the function `dokan_get_page_url` to accept `$subpage` as an extra parameter

### PR DESCRIPTION
**Pull request by strategio**
Transposition of initial PR on our fork (https://github.com/OnTheGoSystems/dokan/pull/2).

- Introduced a new function `dokan_add_subpage_to_url` to avoid the
repetitive issues due to incorrect path concatenation.
- Added- the new subpage argument in the filter hook.

https://github.com/weDevsOfficial/dokan-wpml/issues/13

### CODE REVIEW

**Comment by nurul-umbhiya** [comment]
@strategio I've created a new branch for wpml related issues: https://github.com/weDevsOfficial/dokan/tree/fix/wpml, I would like to suggest you create pull requests on this branch. I've discussed with QA team and they'll test compatibility as soon as possible and will merge on that branch. this way development will be a bit faster.

**Comment by strategio** [comment]
@nurul-umbhiya, I have rebased my branch on `fix/wpml` branch and changed the target branch here.

**Comment by nurul-umbhiya** [comment]
@strategio merged

**Comment by strategio** [comment]
Thanks @nurul-umbhiya.

Now the last remaining PR is https://github.com/weDevsOfficial/dokan-wpml/pull/15 (on Dokan WPML). Could you please take care of it?

**Pull request merged**
