### PR TITLE
new: Store open and closed status add on dokan store listing page

### PR DESCRIPTION
**Pull request by alamgircsebd**
**How look the UI:**

Screenshot_12

**How mange the settings:**

Case 1: This option will show only if Dokan admin setting **Store Opening Closing Time Widget** and vendor setting **Store Opening Closing Time** both enabled 

Case 2: This globally can mange by admin can enable/disable using Dokan admin setting **Store Opening Closing Time Widget**
http://prntscr.com/w6wj18

Case 3: This option can mange by vendor their store only by using vendor setting **Store Opening Closing Time** 
http://prntscr.com/w6wits

### CODE REVIEW

**Comment by tareq1988** [comment]
This status icon is a bit confusing. It'll seem like the store chat is online, not the store is open. It's better to add a label instead of adding online/offline status.

**Comment by alamgircsebd** [comment]
Yes, agree with you, here also included title on mouse hover, Also this one given to UI design team for review hope they can make it more batter.

**Comment by tuhin480** [comment]
Please have a look @alamgircsebd 
https://prnt.sc/wgpg4y

**Comment by alamgircsebd** [comment]
> 
> 
> Please have a look @alamgircsebd
> https://prnt.sc/wgpg4y

Thanks

**Comment by alamgircsebd** [comment]
New UI how look
Screenshot

**Comment by FaraziF** [comment]
Without a store banner image, store open & close status is not readable on the store listing page.
Screenshot 2021-01-13 at 4 41 09 PM

**Comment by alamgircsebd** [comment]
> Without a store banner image, store open & close status is not readable on the store listing page.
> Screenshot 2021-01-13 at 4 41 09 PM

Please run grunt

**Comment by FaraziF** [comment]
Now it's fulfilled the design requirements

Screenshot 2021-01-13 at 6 33 52 PM

**Comment by alamgircsebd** [comment]
Please test it now
Screenshot (1)

**Pull request merged**
