### PR TITLE
fix: Select2 block the input field in dropdown

### PR DESCRIPTION
**Pull request by shohag121**
When the user trying to search or create a tag on the product page the tag field is getting blocked by the dropdown result.

fix: https://github.com/weDevsOfficial/dokan-pro/issues/1172

### CODE REVIEW

**Review by nurul-umbhiya — APPROVED** [review]

**Comment by danielbreves** [comment]
This seems to cause a big gap below the dropdown. Not sure what was the original issue it was trying to fix:

Screen Shot 2021-11-13 at 4 59 26 pm

cc @shohag121 @nurul-umbhiya

**Comment by CasperBraske** [comment]
> This seems to cause a big gap below the dropdown. Not sure what was the original issue it was trying to fix:

I have an add-on for Dokan that uses Select2 and I can confirm this.

image

**Comment by nurul-umbhiya** [comment]
@rajankarmakar can you please look into this issue?

**Comment by rajankarmakar** [comment]
The issue will be fixed once the PR will be marged.
https://github.com/weDevsOfficial/dokan/pull/1446

**Comment by CasperBraske** [comment]
@rajankarmakar  It looks like it will fix the issue in the product edit page, only. Not elsewhere.

**Pull request merged**
