### PR TITLE
Fix admin dashboard feed REST Request error

### PR DESCRIPTION
**Pull request by ediamin**
It happens due to WP 5.5 added some changes in `SimplePie::get_links` method. @sabbir1991 @FaraziF please test for before and after WP 5.5 versions.

You need to clear the transient with the hash `33dfe3053f180bedc95ae6d74eea5ed4` 
Screenshot 2020-08-31 at 5 14 20 PM

### CODE REVIEW

**Review by sabbir1991 — COMMENTED** [review]
Yes, It's working now.

**Comment by tareq1988** [comment]
Thouh this is a dirty fix, it seems a bug of the library. 

@ediamin could you create a trac ticket and inform the WordPress team?

**Comment by ediamin** [comment]
@tareq1988 It's already been reported https://core.trac.wordpress.org/ticket/51056

**Review by FaraziF — COMMENTED** [review]
@ediamin It's working well with WordPress's previous and current versions.

**Pull request merged**
