### PR TITLE
enhance/mutiple-store-times-for-store-widget

### PR DESCRIPTION
**Pull request by MdAsifHossainNadim**
### Update store times widget as multiple time.

Prior to this enhance, the Store Time Widget was not reflected in the widget when the store opened and closed on the Single Store page and it was working for a single time.

Now, after this enhance the store time widget will work more than once when dokan-pro is activated and starts day will working well according to wp settings.

**Video Link:**
http://share.vidyard.com/watch/E37HJPVmExxmnbiPZdP3Wf?

fix: https://github.com/weDevsOfficial/dokan-pro/issues/1753

Related with dokan-pro: https://github.com/weDevsOfficial/dokan-pro/pull/1758

### CODE REVIEW

**Review by xaviranik — APPROVED** [review]

**Comment by Rat01047** [comment]
Issue: Selection box design breaks.

Scenario: When trying to enable Store Opening/Closing times, and selecting the days, Selecting All the days breaks the design.

Screenshot given for reference:
image

**Comment by Rat01047** [comment]
Issue: Time for Store opening-closing design issue.

Scenario: When Store opening-closing is added from widget and from Vendor the times are set. In Store details, the Store opening-closing widget time set design comes under the day name.

Screenshot given for reference:
image

**Comment by Rat01047** [comment]
Issue: Changing the "Week Starts on" from Monday to Tuesday creates a big gap between the Store opening-closing days.

Scenario: Add Store opening-closing multiple days and time > Change the "Week Starts on" from Monday to Tuesday or any other day > Big gap appears.

Screenshot given for reference:
image

**Comment by Rat01047** [comment]
Issue: For any day, after selecting 12AM to 11:59PM the plus sign for adding additional time goes away, but when the time is decreased the plus sign does not reappear.

Scenario: For any day, set the time to12AM to 11:59PM (i.e. the whole day) > the plus (+) sign for adding additional time goes away > But when the time is decreased the plus sign does not reappear, which should be allowed.

Screenshot given for reference:
image

**Pull request merged**
